[[language]]
name = "rust"
auto-format = false
language-servers = ["rust-analyzer"]

[language-server.rust-analyzer.config.completion]
callable = { snippets = "add_parentheses" }
fullFunctionSignatures = { enable = true }

[language-server.rust-analyzer.config.inlayHints]
maxLength = 7
lifetimeElisionHints = { enable = true, useParameterNames = false }

[[language]]
name = "c"
indent = { unit = "    ", tab-width = 4 }

[[language]]
name = "cpp"
indent = { unit = "    ", tab-width = 4 }
