[[language]]
name = "rust"
auto-format = false
language-servers = [ "rust-analyzer", "ltex-ls" ]

[language-server.rust-analyzer.config.completion]
callable = { snippets = "add_parentheses" }
fullFunctionSignatures = { enable = true }

[language-server.rust-analyzer.config.inlayHints]
maxLength = 7
lifetimeElisionHints = { enable = true, useParameterNames = false }

[language-server.ltex-ls]
command = "ltex-ls"

[[language]]
name = "c"
indent = { unit = "    ", tab-width = 4 }

[[language]]
name = "cpp"
indent = { unit = "    ", tab-width = 4 }

[[language]]
name = "markdown"
language-servers = [ "ltex-ls" ]
